development:
  # Configure available database clients. (required)
  clients:
    # Config for the registrations database
    default:
      uri: <%= ENV['WCRS_REGSDB_URI'] || 'mongodb://mongoUser:password1234@localhost:27017/waste-carriers' %>
    # Config for the users database
    users:
      uri: <%= ENV['WCRS_USERSDB_URI'] || 'mongodb://mongoUser:password1234@localhost:27017/waste-carriers-users' %>
  # Configure Mongoid specific options. (optional)
  options:
    raise_not_found_error: false
test:
  clients:
    default:
      uri: <%= ENV['WCRS_REGSDB_URI'] || 'mongodb://mongoUser:password1234@localhost:27017/waste-carriers' %>
    users:
      uri: <%= ENV['WCRS_USERSDB_URI'] || 'mongodb://mongoUser:password1234@localhost:27017/waste-carriers-users' %>
  options:
    raise_not_found_error: false
production:
  clients:
    default:
      uri: <%= ENV['WCRS_REGSDB_URI'] %>
    users:
      uri: <%= ENV['WCRS_USERSDB_URI'] %>
  options:
    raise_not_found_error: false
